import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "@/app/globals.css";
import Orderinformation from "@/components/Orderinformation";
import ScrollableTabs from "@/components/ScrollableTabs";

const poppins = Poppins({
  weight: ['400', '500', '600', '700'], // Specify the font weights you need
  subsets: ['latin'], // Specify the subsets you need
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <main className="min-h-[100dvh]">
          {children}
        </main>
      </body>
    </html>
  );
}
